eCommerceTesco/config/routes.rb
Rails.application.routes.draw do
  resources :customers

  resources :customer_addresses

end

eCommerceTesco/app/models/customer.rb
class Customer < ActiveRecord::Base
end

eCommerceTesco/app/models/customer_address.rb
class CustomerAddress < ActiveRecord::Base
end

eCommerceTesco/app/controllers/customer_addresses_controller.rb
class CustomerAddressesController < ApplicationController
  before_action :set_customer_address, only: [:show, :edit, :update, :destroy]

  # GET /customer_addresses
  # GET /customer_addresses.json
  def index
    @customer_addresses = CustomerAddress.all
  end

  # GET /customer_addresses/1
  # GET /customer_addresses/1.json
  def show
  end

  # GET /customer_addresses/new
  def new
    @customer_address = CustomerAddress.new
  end

  # GET /customer_addresses/1/edit
  def edit
  end

  # POST /customer_addresses
  # POST /customer_addresses.json
  def create
    @customer_address = CustomerAddress.new(customer_address_params)

    respond_to do |format|
      if @customer_address.save
        format.html { redirect_to @customer_address, notice: 'Customer address was successfully created.' }
        format.json { render :show, status: :created, location: @customer_address }
      else
        format.html { render :new }
        format.json { render json: @customer_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_addresses/1
  # PATCH/PUT /customer_addresses/1.json
  def update
    respond_to do |format|
      if @customer_address.update(customer_address_params)
        format.html { redirect_to @customer_address, notice: 'Customer address was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_address }
      else
        format.html { render :edit }
        format.json { render json: @customer_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_addresses/1
  # DELETE /customer_addresses/1.json
  def destroy
    @customer_address.destroy
    respond_to do |format|
      format.html { redirect_to customer_addresses_url, notice: 'Customer address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_address
      @customer_address = CustomerAddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_address_params
      params[:customer_address]
    end
end

eCommerceTesco/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all.page(params[:page])
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :sal)
    end
end

eCommerceTesco/app/helpers/customer_addresses_helper.rb
module CustomerAddressesHelper
end

eCommerceTesco/app/helpers/customers_helper.rb
module CustomersHelper
end

eCommerceTesco/app/views/customer_addresses/_form.html.erb
<%= form_for(@customer_address) do |f| %>
  <% if @customer_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_address.errors.count, "error") %> prohibited this customer_address from being saved:</h2>

      <ul>
      <% @customer_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

eCommerceTesco/app/views/customer_addresses/edit.html.erb
<h1>Editing customer_address</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_address %> |
<%= link_to 'Back', customer_addresses_path %>

eCommerceTesco/app/views/customer_addresses/index.html.erb
<h1>Listing customer_addresses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_addresses.each do |customer_address| %>
      <tr>
        <td><%= link_to 'Show', customer_address %></td>
        <td><%= link_to 'Edit', edit_customer_address_path(customer_address) %></td>
        <td><%= link_to 'Destroy', customer_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer address', new_customer_address_path %>

eCommerceTesco/app/views/customer_addresses/new.html.erb
<h1>New customer_address</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_addresses_path %>

eCommerceTesco/app/views/customer_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_customer_address_path(@customer_address) %> |
<%= link_to 'Back', customer_addresses_path %>

eCommerceTesco/app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sal %><br>
    <%= f.text_field :sal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

eCommerceTesco/app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

eCommerceTesco/app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sal</th>
      <th colspan="3"></th>
    </tr>ramak
  </thead>

  <tbody>
  <%= will_paginate @customers, renderer: BootstrapPagination::Rails %>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.sal %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

eCommerceTesco/app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

eCommerceTesco/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Sal:</strong>
  <%= @customer.sal %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

eCommerceTesco/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ECommerceTesco</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>